/* Hullform component - tbicons.c
 * Copyright (C) 2011 Peter Rye
 * Email: prye@iinet.net.au
 *
 * This code is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed WITHOUT ANY WARRANTY; without 
 * even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Library General
 * Public License for more details.
 *
 * For a copy of the GNU Library General Public License , you can write to:
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
 
/*	Toolbar icons	*/
/* XPM */
static char *confsetcolours_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"o	c #ff0000",
"O	c #800080",
"+	c #0000ff",
"@	c #800000",
"                        ",
"    ..              XX  ",
" oo ..             OXX  ",
" ooo..       ++   OXX   ",
"   o..o      ++  OOXX   ",
"     ..oo    ++ OO XX   ",
"     ..oooo ++ OO XX    ",
"     ..  ooo++OO  XX    ",
"     ..    o+OO   XX    ",
"     ..     OOoooXX     ",
"   @@..    OO  ooXX     ",
"    @..   OO+    XXoo   ",
"     @.. OO++   XX oooo ",
"      ..OO ++   XX   o  ",
"      ..@  ++   XX      ",
"      ..@@++   XX       ",
"     O.. @@+   XX       ",
"    OO..  @@   XX       ",
"   OO  .. +@@ XX        ",
"  OO   ..++ @@XX        ",
"       ..++  @XX        ",
"       ..++  XX@        ",
"             XX@@       ",
"                        "};
/* XPM */
static char *confsetfont_xpm[] = {
"24 24 3 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"               ..       ",
"               ..X      ",
"              X..X      ",
"              ....      ",
"             ..X..      ",
"            X.. ..X     ",
"            ..  X.X     ",
"           ..X   ..     ",
"          X..    ..     ",
"          ..     X.X    ",
"         ..X      .X    ",
"        X..       ..    ",
"        ..        ..    ",
"       ..X        X.X   ",
"      ..X          .X   ",
"     X..           ..   ",
"     ..            X.   ",
"    .................X  ",
"   X.................X  ",
"   ..               ..  ",
"  ..X               X.  ",
" X..                X.. ",
" ..                  .. ",
"....                ...."};
/* XPM */
static char *confsetlinestyles_xpm[] = {
"24 24 2 1",
" 	c #ffffff",
".	c #000000",
"                        ",
"       ..             ..",
"       ..            ...",
"        ..          ... ",
"        ..          ..  ",
"         ..             ",
"         ..      ..     ",
"          ..    ...     ",
"..        ..   ...      ",
"....       ..  ..       ",
"  ....     ..         ..",
"    ..  ..  ..    ..  ..",
"        ........  ..    ",
"         .......        ",
"        ........        ",
"    ..  ..   .....      ",
"..  .. ..     ......    ",
"..    ...      .. ..    ",
"     ...       ..     ..",
"     ..         ..    ..",
"                ..      ",
"  ..             ..     ",
" ...             ..     ",
"...                     "};
/* XPM */
static char *confsetplotter_xpm[] = {
"24 24 5 1",
" 	c #c0c0c0",
".	c #000000",
"X	c #ff0000",
"o	c #808080",
"O	c #ffffff",
"                        ",
"     ......  XXXXXX     ",
"    o OO o.XXXXXXXXXX   ",
"    o OO oXXXXXXXXXXXX  ",
"    o OO XXXXX     XXXX ",
"ooooo OO XXXo       XXXX",
"....o OOXXXX.        XXX",
"........XXX..        XXX",
".............        XXX",
".............       XXXX",
".............      XXXX ",
"   oo.......o     XXXX  ",
"    o OO o..     XXXX   ",
"    o OO oo.    XXXX    ",
"    o OO o..    XXX     ",
"     ooooo.    XXXX     ",
"     oO  o.    XXX      ",
"     oO  o.    XXX      ",
" OOOOOooo.OOOOOXXX      ",
"O...... .....OOO        ",
"OOOOOOO .OO.OOOOO       ",
"OOOOOOO .O.OOOOXXX      ",
"OOOOOOO ..OOOOOXXXO     ",
"OOOOOOOOOOOOOOOXXXO    O"};
/* XPM */
static char *draggerritsma_xpm[] = {
"24 24 3 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"                        ",
"                        ",
"                        ",
"                        ",
".XX.                    ",
"X  X                    ",
"X  X                    ",
"X  X             X  X   ",
"X                   X   ",
"X    .X. X X X X X XXX  ",
"X    X X XX  XX  X  X   ",
"X XX X X X.  X.  X  X   ",
"X XX X X X   X   X  X   ",
"X  X X X X   X   X  X   ",
"X  X XXX X   X   X  X   ",
"X  X X   X   X   X  X   ",
"X  X X   X   X   X  X   ",
"X  X X   X   X   X  X   ",
"X  X X X X   X   X  X XX",
".XX. .X. X   X   X  X XX",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *dragholtrop_xpm[] = {
"24 24 3 1",
" 	c #c0c0c0",
".	c #000000",
"X	c #808080",
"                        ",
"                        ",
"                        ",
"                        ",
". .     .               ",
". .     .               ",
". .     .               ",
". .     .  .            ",
". .     .  .            ",
". . X.X . ... .X.X.X X.X",
". . . . .  .  .. . . . .",
"... . . .  .  .X . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . . . .  .  .  . . . .",
". . X.X .  .  .  X.X ..X",
"                     .  ",
"                     .  ",
"                     .  ",
"                        "};
/* XPM */
static char *dragoortmerrssen_xpm[] = {
"24 24 3 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"                        ",
"                        ",
"                        ",
"                        ",
".XX.                    ",
"X  X                    ",
"X  X                    ",
"X  X         X          ",
"X  X         X          ",
"X  X .X. X XXXX XXXX.   ",
"X  X X X XX  X  X X X   ",
"X  X X X X.  X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X   ",
"X  X X X X   X  X X X XX",
".XX. .X. X   X  X X X XX",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *dragplot_xpm[] = {
"24 24 5 1",
" 	c #000000",
".	c #c0c0c0",
"X	c #0000ff",
"o	c #ffffff",
"O	c #000000",
"  .XXXXXXXXXXXXXXXXXXXXX",
" . XoooooooooooooooooooX",
" . XooooooooooooooooooOX",
"  .XXoooooooooooooooooOX",
"...XoooooooooooooooooOoX",
"   XoooooooooooooooooOoX",
" . XooooooooooooooooOooX",
"   XXooooooooooooooOoooX",
"  .XoooooooooooooOOooooX",
" . XoooooooooooOOooooooX",
"...XooooooooooOooooooooX",
"   XXooooooooOoooooooooX",
" . XoooooooooOoooooooooX",
"   XooooooooOooooooooooX",
" . XoooooooOoooooooooooX",
"...XXoooooOooooooooooooX",
"   XooooOOoooooooooooooX",
" ..XooOOoooooooooooooooX",
" . XOOoXoooXoooXoooXoooX",
"   XXXXXXXXXXXXXXXXXXXXX",
"....   .   .   .   .  ..",
".... ... . .  ..  .. . .",
"..... ..   .  ..  .. . .",
"....   . ...   .   .  .."};
/* XPM */
static char *dragsavitskybrown_xpm[] = {
"24 24 3 1",
" 	c #808080",
".	c #000000",
"X	c #c0c0c0",
" .. XXXXXXXXXXXXXXXXXXXX",
".XX.XXXXXXXXXXXXXX .. XX",
".XXXXXXXXXXXXXXXXX.XX.XX",
".XXXXXXXXXXXXXXXXX.XX.XX",
".XXXX ...X.XXX.XXX.X. XX",
" .. X.XX.X.XXX.XXXX. XX.",
"XXX.X.XX.X.XXX.XXX.X. X.",
"XXX.X.XX.X. X .XXX.XX.. ",
"XXX.X.XX.X .X. XXX.XX..X",
".XX.X.XX.XX. .X..X.XX.. ",
" .. X ...XX . X..X .. X.",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"... XXXXXXXXXXXXXXXXXXXX",
".XX.XXXXXXXXXXXXXXXXXXXX",
".XX.XXXXXXXXXXXXXXXXXXXX",
".XX.XXXXXXXXXXXXXXXXXXXX",
".XX.X...X .. X.XXX.X...X",
"...XX.XX..XX.X.XXX.X.XX.",
".XX.X.XXX.XX.X.XXX.X.XX.",
".XX.X.XXX.XX.X.X.X.X.XX.",
".XX.X.XXX.XX.X.X.X.X.XX.",
".XX.X.XXX.XX.X.X.X.X.XX.",
"... X.XXX .. X .X. X.XX."};
/* XPM */
static char *dragsavitsky_xpm[] = {
"24 24 3 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"                        ",
"                        ",
"                        ",
"                        ",
" .XX.                   ",
" X  X                   ",
" X                      ",
" X               X  X   ",
" X                  X   ",
" X     .XX X   X X XXX  ",
" .XX. .X X X   X X  X   ",
"    X X. X X   X X  X   ",
"    X X  X X. .X X  X   ",
"    X X  X X. .X X  X   ",
"    X X  X .X X. X  X   ",
"    X X  X .X X. X  X   ",
"    X X  X  X X  X  X   ",
"    X X  X  .X.  X  X   ",
" X  X X  X  .X.  X  X XX",
" .XX. .XXX   X   X  X XX",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *editcatamaranconvert_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #0000ff",
"X	c #000000",
"o	c #000080",
"O	c #008080",
"                        ",
"                        ",
"                        ",
"      ............      ",
"     .XXX.XXXX.XXX.     ",
"     .XXX.XXXX.XXX.     ",
"    .XXXX.XXXX.XXXX.    ",
"    .XXXX.XXXX.XXXX.    ",
"   .XXXXX.XXXX.XXXXX.   ",
"   ..................   ",
" oXXXo............oXXXo ",
"XX.X.XX..........XX.X.XX",
"...X....OO    OO....X...",
"...X...O        O...X...",
"..oXo..          ..oXo..",
".o.X.o.          .o.X.o.",
"o..X..o          o..X..o",
" ..X..            ..X.. ",
"  .X.              .X.  ",
"   X                X   ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *editcatamaranmovehulls_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #0000ff",
"o	c #ff0000",
"         .........      ",
".........XXXX.XXXX..... ",
"XXXXXXXXXXXXX.XXXXXXXX. ",
"XXXXXXXXXXXXX.XXXXXXXX. ",
".....XXXXXXXX.XXXXXXXX. ",
"     .XXXXXXX.XXXXXXX.  ",
"     .XXXXXXX.XXXXXXX.  ",
"     .XXXXXXX.XXXXXXX.  ",
"      .XXXXXX.XXXXXX.   ",
"      .XXXXXX.XXXXXX.   ",
"      .XXXXXX.XXXXXX.   ",
"       .XXXXX.XXXXX.    ",
"       .XXXXX.XXXXX.    ",
"       .XXXXX.XXXXX.    ",
"        ..XXX.XXX..     ",
"          ..X.X..       ",
"            ...         ",
"     .              .   ",
"    .o..............o.  ",
"   .oooooooooooooooooo. ",
"  .oooooooooooooooooooo.",
"   .oooooooooooooooooo. ",
"    .o..............o.  ",
"     .              .   "};
/* XPM */
static char *editcopytoclipboard_xpm[] = {
"24 24 7 1",
" 	c #c0c0c0",
".	c #ffffff",
"X	c #808080",
"o	c #808000",
"O	c #ffff00",
"+	c #000000",
"@	c #008080",
"         .....X         ",
"   ooooooo.. Xooooooo   ",
"  ooOOOO...  XXOOOOOoo  ",
"  oOXXX+..    XX+XX+Oo  ",
"  oOX..++++++++++ .+Oo  ",
"  oOX..@          .+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX@@@@@@@@@@@@@@+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX@@@@@@@@@@@@@@+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX@@@@@@@@@@@@@@+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX@@@@@@@@@@@@@@+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX..@...........+Oo  ",
"  oOX@@@@@@@@@@@@@@+Oo  ",
"  oOX..@...........+Oo  ",
"  oO++++++++++++++++Oo  ",
"  ooOOOOOOOOOOOOOOOOoo  ",
"   oooooooooooooooooo   "};
/* XPM */
static char *editlineinsert_xpm[] = {
"24 24 8 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #008080",
"o	c #0000ff",
"O	c #808080",
"+	c #000000",
"@	c #800000",
"#	c #ff0000",
"                        ",
"               .XXoooooo",
"           .XXoooXXX   o",
"         XoooXX        o",
"       .ooX           Xo",
"     .ooX             Xo",
"    .oX               oX",
"   .oX            .O++oX",
"   oX          .O+@###o.",
"  o.         .O+###++Xo ",
" .o        .+@##@+O. Xo ",
" o.      .+@##+O.    oX ",
".o      ++##+O.      o. ",
"o.     +@#+O.       .o. ",
"o     +#@+.         .o  ",
"o    +#+.           o.  ",
".o  +#+            .o   ",
" o +#+             o.   ",
" o+#+             o.    ",
"  o+            Xo.     ",
"  oX        .Xoo.       ",
"   oo   .Xooo..         ",
"    .oooo..             ",
"                        "};
/* XPM */
static char *editlineproperties_xpm[] = {
"24 24 8 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"O	c #008080",
"+	c #0000ff",
"@	c #800000",
"#	c #ff0000",
"  .XooooX.              ",
" XooooooooX    .OO++++++",
"XooX.  .XooXOO+++OOO   +",
"ooX      Xoo+OO        +",
"oo.    .++oo          O+",
"oo   .++O.oo          O+",
"    .+O Xoo.          +O",
"   .+OXoooX       .Xoo+O",
"   +OXooo.     .Xo@###+.",
"  +. oo.     .Xo###ooO+ ",
" .+  oo    .o@##@oX. O+ ",
" +.      .o@##oX.    +O ",
".+   oo oo##oX.      +. ",
"+.   ooo@#oX.       .+. ",
"+     o#@o.         .+  ",
"+    o#o.           +.  ",
".+  o#o            .+   ",
" + o#o             +.   ",
" +o#o             +.    ",
"  +o            O+.     ",
"  +O        .O++.       ",
"   ++   .O+++..         ",
"    .++++..             ",
"                        "};
/* XPM */
static char *editmultiplyadd_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #ff0000",
"                        ",
"                        ",
"          ..            ",
"          ..            ",
"          ..            ",
"  ..X     .. oo  X..    ",
"  ....X   .. oo ....    ",
"   X....X .. oo...X     ",
"     X.......oo.X       ",
"       X.....oo         ",
"       X.....oo         ",
"     X.......oo         ",
"   X..oooooooooooooooo  ",
"  ....oooooooooooooooo  ",
"  ..X     .. oo  X..    ",
"          .. oo         ",
"          .. oo         ",
"          .. oo         ",
"          .. oo         ",
"             oo         ",
"             oo         ",
"             oo         ",
"                        ",
"                        "};
/* XPM */
static char *editmultiply_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #ff0000",
"X	c #c0c0c0",
"o	c #808080",
"O	c #000000",
"+	c #800000",
"                        ",
"                        ",
".    .  XoOOOOoX  .    .",
".   ..OOoXXOOXXoOO..   .",
". O... +   OO   + ...O .",
".O.... +   OO   + ....O.",
"........................",
"........................",
"........................",
". ....  +  OO  +  ....X.",
".O ...+  + OO +  +... o.",
".O +..+  + OO +  +..+ O.",
".O  +. + OOOOOO + .+ XO.",
".oO +  OO +OO+ OO  + oo.",
".XO  OO +  OO  + OO  OX.",
". oOO+   + OO +   +OOo .",
". XO  +   +OO+   +  OX .",
".  oO  +   OO   +  Oo  .",
".   oO  +  OO  +  Oo   .",
".    XOOX++OO++XOOo    .",
"       XOOOOOOOOX       ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *editorientatelines_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #808080",
"O	c #ff0000",
" ....X                  ",
" .ooo....X              ",
" .oooOoo ...X           ",
" .oooOoooOo ...X        ",
" .oooOoooOoooO ..X      ",
" .oooOoooOoooOoo...     ",
" . ooOoooOoooOooooO.    ",
" . oooOoooOoooOoooOo.   ",
" X.oooOoooOoooOooooOo.  ",
"  .oooOoooOooooOoooOoo. ",
"  .oooOooooOoooOooooOo.X",
"  .oooOooooOooooOoooOoo.",
"  . oooOoooOooooOooooOo.",
"  X.oooOooooOooooOoooOo.",
"   .oooOooooOooooOooooO.",
"   . oooOooooOooooOoooO.",
"   X.oooOooooOooooOooo .",
"    . oooOooooOooooOooXX",
"    X.oooOooooOooooOoo. ",
"     . oooOooooOooooO.X ",
"     X.oooOooooOooooO.  ",
"      . oooOooooOo...   ",
"      X. ooOo.....X     ",
"       ......X          "};
/* XPM */
static char *editsectcentre_xpm[] = {
"24 24 2 1",
" 	c #ffffff",
".	c #000000",
"                        ",
"                        ",
"         ......         ",
"     ....  ..  ....     ",
"  ...  .   ..   .  ...  ",
" .. .  .   ..   .  . .. ",
". . .  .   ..   .  . . .",
". . .   .  ..  .   . . .",
". .  .  .  ..  .  .  . .",
".  . .  .  ..  .  . .  .",
" . .  .  . .. .  .  . . ",
" . .  .  . .. .  .  . . ",
" .  .  . ...... .  .  . ",
"  . .  .. .... ..  . .  ",
"  .  .. .  ..  . ..  .  ",
"   ...   . .. .   ...   ",
"   .  .   ....   .  .   ",
"    .  .   ..   .  .    ",
"     .  .  ..  .  .     ",
"      .. ...... ..      ",
"        ........        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *editsectcontrol_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #ff0000",
"X	c #808080",
"o	c #000000",
"O	c #0000ff",
"+	c #00ffff",
"@	c #c0c0c0",
"                  ...   ",
"                 .....  ",
"                ..XoX.. ",
"                ..oOo.. ",
"                ..XOX.. ",
"                 .OO..  ",
"                  OO.   ",
"                 oOo    ",
"                 oO     ",
"                XOO     ",
"                oO+     ",
"               ooO+     ",
"              XooO      ",
"             @ooOO      ",
"            @oo@O+      ",
"           @ooOOO+      ",
"          XooOOOOO      ",
"  ...    ooo@OOooooooo  ",
" ..... XooOOOOOo   oX@  ",
"..XoXoOOOOOO+ Oo  @oX   ",
"..oOOOOO+      o @ @oX  ",
"..XoX..        ooo@ @oo ",
" .....         oXXo@oo  ",
"  ...          o@ Xoo   "};
/* XPM */
static char *editsectdouble_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"                        ",
"                        ",
"                        ",
"              .XoooX.   ",
"             ooooooooX  ",
"            .ooooooooo. ",
"            oooo. .oooX ",
"            ooo    .ooo ",
" ooX    Xoo        .ooo ",
" ooo.  .ooo        .ooX ",
"  ooo  ooo.       .ooo. ",
"  XooooooX       .ooo.  ",
"   oooooo       .ooo.   ",
"   .oooo.      .ooo.    ",
"   .oooo.     .ooo.     ",
"   oooooo    .ooo.      ",
"  XooooooX   ooo.       ",
"  ooo  ooo. .oooooooooo ",
" ooo.  .ooo ooooooooooo ",
" ooo    ooo ooooooooooo ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *editsectedit_xpm[] = {
"24 24 4 1",
" 	c #c0c0c0",
".	c #404040",
"X	c #000000",
"o	c #808080",
"     .                  ",
"     .  X               ",
"     .  X  X            ",
"    .   X  X            ",
"    .   X  X  X         ",
"    .  X   X  X  X      ",
"    .  X  X   X  X      ",
"   .   X  X  X   X  .   ",
"   .   X  X  X  X   .   ",
"   .   X  X  X  X   .  .",
"   .   X  X  X  X  .   .",
"  ..  X   X  X  X  .   .",
" ..   X  XXXXXXXXXXXX . ",
".     X  X        oX  . ",
"    XX   X       oXo  . ",
"   X     X      oXo   . ",
" XX    XXX     oXo.   . ",
"X    XX  X      oXo  .  ",
"    X    X   o   oXo .  ",
"  XX     X  oXo  .oXo.  ",
" X      XX oXoXo .ooXo  ",
"      XX XoXo oXo.oXo   ",
"    XX   XXo   oXoXo.   ",
"  XX    XXo   ..oXo..   "};
/* XPM */
static char *editsectfollow_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #000000",
"X	c #c0c0c0",
"o	c #808080",
"O	c #ff0000",
"             .          ",
"             ..         ",
"            X...o       ",
"            X....o      ",
"            o.....X     ",
"            .......     ",
"            ....oX      ",
"             X...       ",
"            O....       ",
"            OOOOo       ",
"          OOo.oOO       ",
"          OO...OO       ",
"          OOo.oOO       ",
"           O..OO        ",
"           X..O         ",
"           ..X          ",
"          ...           ",
"  OOO    ...X           ",
" OOOOO X...X            ",
"OOo.o.....              ",
"OO......X               ",
"OOo.oOO                 ",
" OOOOO                  ",
"  OOO                   "};
/* XPM */
static char *editsecthalf_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #c0c0c0",
"           ...          ",
"          X...          ",
"         .....          ",
"        ......          ",
"        .. ...    o..   ",
"           ...    ...   ",
"           ...   ...    ",
"           ...   ..o    ",
"..X    X.. ...  ...     ",
"...o  o... ...  ..o     ",
" ...  ...o ... ...      ",
" X......X     o..o      ",
"  ......      ...       ",
"  o....o     ...o X..X  ",
"  o....o     ... ...... ",
"  ......    ... ..o o...",
" X......X   ... ..   ...",
" ...  ...o ...      o...",
"...o  o... ...     o... ",
"...    ... ..     o...  ",
"                 o...   ",
"                o...    ",
"                ........",
"                ........"};
/* XPM */
static char *editsecthelp_xpm[] = {
"24 24 3 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"                        ",
"        ..XXXX..        ",
"      .XXXXXXXXXX.      ",
"     .XXXXXXXXXXXX.     ",
"     XXXX..  ..XXXX     ",
"    .XXX.      .XXX.    ",
"    XXX.        .XXX    ",
"    XXX.        .XXX    ",
"                .XXX    ",
"               .XXX.    ",
"              .XXXX     ",
"             .XXXX.     ",
"            .XXXX.      ",
"            XXXX.       ",
"           .XXX.        ",
"           XXX.         ",
"           XXX.         ",
"           XXX          ",
"           XXX          ",
"                        ",
"                        ",
"           XXX          ",
"           XXX          ",
"           XXX          "};
/* XPM */
static char *editsectionadd_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #00ffff",
"X	c #008080",
"o	c #0000ff",
"O	c #ff0000",
"+	c #800000",
"                        ",
"              ..XXoooooo",
"          ..XXoooXXX   o",
"        .XoooXX        o",
"       .ooX           Xo",
"     .ooX             Xo",
"    .oO+              o.",
"   .oXO+              o.",
"  .oX+O+              o ",
"  o  +O+             Xo ",
" .o  +O+             Xo ",
" o    +O+            o. ",
" o    +O+            o. ",
"o     +O+           Xo  ",
"o      +O+          Xo  ",
"o      +O+          o.  ",
".o      +O+        Xo   ",
".o      ++O+       o    ",
" o       ++O++++  o     ",
" .o       ++OOOOoo      ",
"  oX       +++++.       ",
"  .oo   Xoooo.          ",
"    .oooo..             ",
"                        "};
/* XPM */
static char *editsectiondelete_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #008080",
"X	c #0000ff",
"o	c #808080",
"O	c #ff0000",
"+	c #000000",
"@	c #808080",
"                        ",
"              ....XXXXXX",
"          ....XXX...oooX",
"        ..XXX..ooooooooX",
"       .XX.Ooooooooooo.X",
"     .XX.ooOoooooooooo.X",
"    ++Ooooo++oooooooooX.",
"   .++Oooo@++oooooooooX.",
"  .X@++ooo++OoooooooooX ",
"  Xoo++@o@++Ooooooooo.X ",
" .Xoo@++o++@oOooooooo.X ",
" XOooo++@++ooOoooooooX. ",
".XOooo@+++@oooOooooooX. ",
"XoOooo@+++ooooOooooo.X  ",
"XoOoooo+++oooooOoooo.X  ",
"XooOoo@+++@oooooOoooX.  ",
".XoOoo++@++ooooooOO.X   ",
".XoOo@++o++@oooooooX    ",
" XooO++@o@++ooooooX     ",
" .Xo@++ooo++OOOOXX      ",
"  X.++Oooo@++XXX.       ",
"  .X++oOOXX++.          ",
"    .XXXX..             ",
"                        "};
/* XPM */
static char *editsectionsedit_xpm[] = {
"24 24 5 1",
" 	c #c0c0c0",
".	c #0000ff",
"X	c #ff0000",
"o	c #000000",
"O	c #808080",
"                        ",
" .                   X  ",
" .                  XXX ",
" .                   X  ",
" .                   o  ",
"                    o   ",
" .                  o   ",
"                    o   ",
" .                  o   ",
" .                 o    ",
" .                 o    ",
"                   o    ",
" .                o     ",
"                  o     ",
" .                o     ",
" .               X      ",
" .              XXX     ",
"                ooooooo ",
" .             o oOOOo  ",
"             oo  oOOOo  ",
" .         oo    oOOOOo ",
" X     oooo      oooOOOo",
"XXXoooo          o  oOo ",
" X                   o  "};
/* XPM */
static char *editsectmaster_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"o	c #c0c0c0",
"O	c #ff0000",
"                        ",
"                        ",
"       .XXXXXXXXXXXXX.  ",
"       .XXXXXXXXXXXXX.  ",
"       .X.         .X.  ",
"       .X.         .X.  ",
"       .X.         .X.  ",
"     XXXXXXX     XXXXXXX",
"      XXXXX       XXXXX ",
"       XXX         XXX  ",
"        X           X   ",
"                        ",
"                        ",
"                        ",
"      o.XXXXXXX.o       ",
"  o.XXXXXO  O..XXXo     ",
"XXXXOo OXO  O   OoXXo   ",
"Xo  O  OXO  O   O  OXo  ",
"X   O  OXO  O   O  OXXo ",
"X   O  OXO  O   O  OXO  ",
"X   O  OXO  O   O  OXOoX",
"XOOOO OOXOOOOO OOO OXOOO",
"                        ",
"                        "};
/* XPM */
static char *editsectoffset_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #ff0000",
"O	c #c0c0c0",
"                     .. ",
"                    X.. ",
"                    ..X ",
"                   X..  ",
"                   ..X  ",
"                  X..   ",
"                  ..X   ",
"                 X..    ",
"                 ..X    ",
"                X..     ",
"             X....X     ",
"            .oooo.      ",
"           .oooooo.     ",
"          XooooooooX    ",
"          .ooo...oo.    ",
"       OX..ooo.  X..X   ",
"    OX.....ooo.     ..  ",
" OX.....XO .oo.    ..   ",
".....XO     .o.   O.    ",
"..XO         X. .. O.   ",
"              .. X. .XO ",
"                  .  .  ",
"                   ..   ",
"                   O    "};
/* XPM */
static char *editsectquit_xpm[] = {
"24 24 8 1",
" 	c #800000",
".	c #008000",
"X	c #808080",
"o	c #000000",
"O	c #ff0000",
"+	c #c0c0c0",
"@	c #808080",
"#	c #00ff00",
"                        ",
"                        ",
"   ...XXooooooo         ",
"   .......XXooo         ",
"   ...........o         ",
"   ...........o         ",
"   ...........o         ",
"   ...........o   O     ",
"   ...........o  OO     ",
"   ...........o OOO     ",
"   ...........oOOOOOOO  ",
"   ...........OOOOOOOO  ",
"   .......+X+.OOOOOOOO  ",
"   .......XoX.oOOOOOOO  ",
"   .......+X+.o OOO     ",
"   ...........o  OO     ",
"   ...........o   O     ",
"   ...........o         ",
"   ...........o         ",
"   ...........o         ",
"@@@@@##.......@@@@@@@@@@",
"@@@@@@@@@##...@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */
static char *editsectredraw_xpm[] = {
"24 24 6 1",
" 	c #000000",
".	c #ff0000",
"X	c #ffffff",
"o	c #ffff00",
"O	c #c0c0c0",
"+	c #808080",
"   ......    XXXXXXXXXXX",
"X   .....    XXXXXXXXXXX",
"X   ......    XXXXXXXXXX",
"XX   .....    XXXXXXXXXX",
"XX   ......    XXXXXXXXX",
"XXX   .....    XXXXXXXXX",
"XXX   ......    XXXXXXXX",
"XXXX   .....    XXXXXXXX",
"XXXX   ......    XXXXXXX",
"XXXXX   .....    XXXXXXX",
"XXXXX    .....    XXXXXX",
"XXXXXX   .....    XXXXXX",
"XXXXXX    .....    XXXXX",
"XXXXXXX   ...    o XXXXX",
"XXXXXXX    . OoO O XXXXX",
"XXXXXXXX    OoOoOo XXXXX",
"XXXXXXXX    oOoOoO XXXXX",
"XXXXXXXXX  o+oOoOo XXXXX",
"XXXXXXXXXXX o+oOoO XXXXX",
"XXXXXXXXXXXX o+oO  XXXXX",
"XXXXXXXXXXXXX+ +   XXXXX",
"XXXXXXXXXXXXXXX    XXXXX",
"XXXXXXXXXXXXXXXX   XXXXX",
"XXXXXXXXXXXXXXXXX+ XXXXX"};
/* XPM */
static char *editsectshow_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #ff0000",
"o	c #000000",
"O	c #808080",
"     . XX               ",
"     . XX XX            ",
"     . XX XX            ",
"    .  XX XX XX  .ooo.  ",
"    .  XX XX XX OoooooO ",
"    . XX  XX XX.ooooooo.",
"    . XX XX  XXoooo oooo",
"   .  XX XX  XXooo  .ooo",
"   .  XX XX XX ooo  .ooo",
"   .  XX XX XX ooo  .ooo",
"   .  XX XX XX  XX Oooo.",
"  .. XX  XX XX  XX.oooO.",
" ..  XX  XX XX  XXooo. .",
".   XXX XX  XX XX ooo  .",
"   XXX  XX  XX XX  .   .",
" XXX    XX XX  XX OoO  .",
"XXX    XXX XX  XX ooo  .",
"X    XXXX  XX  XX OoO . ",
"   XXXX   XXX  XX  .  . ",
" XXXX   XXXX   XX .   . ",
"XXX   XXXX   XXXX .   . ",
"X   XXXX   XXXXX  .   . ",
"  XXXX   XXXX    ..   . ",
"XXXX  XXXXX   ...     . "};
/* XPM */
static char *editsecttextmode_xpm[] = {
"24 24 3 1",
" 	c #ffffff",
".	c #000000",
"X	c #c0c0c0",
" .X X.           ....   ",
" X.X.X             .X   ",
"  X.X             .X    ",
"   .             ....   ",
"                        ",
" .    ...     .   ...   ",
" .    . .     .     .   ",
" .    . .     .   ..    ",
" .  . ...   . .   ...   ",
"                        ",
"...   ...     ... ...   ",
"  .   . .       .   .   ",
" .    . .      .   .    ",
"... . ...   . ... ...   ",
"                        ",
"...   ...     ...  .    ",
" ..   . .      ..  .    ",
" ..   . .      ..  .    ",
"... . ...   . ...  .    ",
"                        ",
". .   ...     ... ...   ",
". .   . .      .. ...   ",
"...   . .      ..   .   ",
"  . . ...   . ... ...   "};
/* XPM */
static char *editsectundo_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #000000",
"X	c #ff0000",
"o	c #808080",
"O	c #c0c0c0",
"+	c #800000",
"@	c #804000",
"         ..             ",
"        ...             ",
"       ....             ",
"      ..X..             ",
"     ..XX..             ",
"    ..XXX........oO     ",
"   ..XXXX...........    ",
"  ..XXXXXXXXXXXXXX+..   ",
" ..XXXXXXXXXXXXXXX+X.O  ",
"..XXXXXXXXXXXXXXXX+X+o  ",
"..XXXXXXXXXXXXXXXX+X+.  ",
" ..XXXXXXXXXXXXXXX+X+.  ",
"  ..XXXXX.........+X+.  ",
"   ..XXXX...........+.  ",
"    ..XXX..ooooooo..+.  ",
"    o..XX..@@@@@@+@+..  ",
"    o@..X..@@@@@@+@+..  ",
"    o@@....@@@@@@+@++.  ",
"    o@@@...@@@@@@+@++.  ",
"    o@@@@..@@@@@@+@+oo  ",
"    o@@@@@.@@@@@@+@+o   ",
"    o@@@@@@@@@@@@+oo    ",
"    oooooooooooooo      ",
"                        "};
/* XPM */
static char *editsectzoom_xpm[] = {
"24 24 6 1",
" 	c #ff0000",
".	c #c0c0c0",
"X	c #ffffff",
"o	c #000000",
"O	c #800000",
"+	c #808080",
"                  ......",
" XXXXXXXXXXXXXXXX ......",
" oooooooooooooooX  .....",
" XXXXXXXXXXXXXXoX ......",
" XXXXXXXXXXXXXXoX . ....",
" XXXXXXXXXXXXXoXX ......",
" XXXXXXXXXXXXXoXX .. ...",
" XXXXXXXXXXXXoXXX ......",
" XXXXXXXXXXXXoXXX ... ..",
" XXXXXXXXXoooXXXX ......",
" XXXXXXoooXXoXXXX .... .",
" XXXoooXXXXoXXXXX ......",
" oooXXXXXXXoXXXXX ..... ",
" XXXXXXXXXoXXXXXX OOOOOO",
" XXXXXXXXoXXXXXXX XXXXXO",
" XXXXXXooXXXXXXXX +++++O",
" XXXXooXXXXXXXXXX XXXX+O",
"                  XXX+XO",
".. ..........OXXXX XX+XO",
".... ........OXXX++ +XXO",
"...... ......O+++XXX XXO",
"........ ....OXXXXX+X XO",
".......... ..OXXX++XXX O",
"............ OOOOOOOOOOO"};
/* XPM */
static char *editstemradius_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #c0c0c0",
"o	c #ff0000",
" ....XXXXXXXXXXXXXXXXXXX",
"     ....XXXXXXXXXXXXXXX",
"         ...XXXXXXXXXXXX",
"            ...XXXXXXXXX",
"               ..XXXXXXX",
"                 ..XXXXX",
"                   .XXXX",
"                    .XXX",
"                    .XXX",
"                     .XX",
"             oo      .XX",
" ..  ..  .. o..o ..  .XX",
" ..  ..  .. o..o .oo .XX",
"             oooo oo .XX",
"               ooooo .XX",
"                oooo.XXX",
"              oooooo.XXX",
"              ooooooXXXX",
"                 ..XXXXX",
"               ..XXXXXXX",
"            ...XXXXXXXXX",
"         ...XXXXXXXXXXXX",
"     ....XXXXXXXXXXXXXXX",
" ....XXXXXXXXXXXXXXXXXXX"};
/* XPM */
static char *edittransom_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #000000",
"X	c #c0c0c0",
"o	c #00ffff",
"O	c #008080",
"+	c #808080",
"                 .XXXXXX",
"                  .XXXXX",
"                   .XXXX",
"                   .XXXX",
"                    .XXX",
"                    ..XX",
"                  ..o.XX",
"               X..Ooo.XX",
"            X...Ooooo.XX",
"        X+...Ooooooooo.X",
".   X+....Oooooooooooo.X",
"o.....+Ooooooooooooooo.X",
"oo.ooooooooooooooooooo.X",
"ooo.ooooooooooooooooooo.",
"oooo.oooooooooooooooooo.",
".ooo+.ooooooooooooooooO.",
"X.+oo.+ooooooooooooooo.X",
"XXX.oo.ooooooooooooooO.X",
"XXXX.OO.ooooooooooooO.XX",
"XXXXX+.O.oooooooooO..XXX",
"XXXXXXX...ooooOO...XXXXX",
"XXXXXXXXX.......XXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX"};
/* XPM */
static char *filebuildersoffsets_xpm[] = {
"24 24 5 1",
" 	c #000000",
".	c #c0c0c0",
"X	c #ffff00",
"o	c #808080",
"O	c #808080",
"             ...........",
" ....... ....      .....",
" ...... . ...... ..    .",
"  .... ... .... ..... . ",
" . .. ..... ... .... .. ",
" ..  ....... . ..... .. ",
" .   ........  .... .. .",
"  ... ......   .... .. .",
" .....  ... ... .. .. ..",
" ....... XXXXXX .. .. ..",
" ....    XXXXXX.  ... ..",
"     ....XXXXXX.   . ...",
" ...XXXXXXXXXXXXXXXX ...",
" ....XXXXXXXXXXXXXX.....",
" .... XXXXXXXXXXXX......",
"     ..XXXXXXXXXX.......",
"       .XXXXXXXX........",
"....oooO.XXXXXXOOooo....",
"...oooOOO.XXXXo.OOooo...",
"..ooooOOOO.XXO.O.Ooooo..",
".oooooooooooooooooooooo.",
"oooooooooooooooooooooooo",
"o                      o",
".                      ."};
/* XPM */
static char *filedynamicwaterline_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"o	c #808080",
"O	c #0000ff",
"+	c #00ffff",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"             ..XXXXXXXXX",
"      ..XXXXXXXooooooooX",
"XXXXXX.. ooooooooooooooX",
"XoooooooooooooooooooooX.",
"OooooooooooooooooooooXXO",
"XOOoooooooooooooooooOOO ",
"X++OOOOOoooooooOOOOO+X +",
"X+++++++OOOOOOO+++++X.++",
"X++++++++++++++++++.X+++",
"+XXXX.. +++++++++XXX++++",
"+++++..XXXXXXXXXXX.+++++",
"++++++++++++++++++++++++",
"++++++++++++++++++++++++",
"++++++++++++++++++++++++",
"++++++++++++++++++++++++",
"++++++++++++++++++++++++",
"++++++++++++++++++++++++"};
/* XPM */
static char *fileexit_xpm[] = {
"24 24 8 1",
" 	c #800000",
".	c #008000",
"X	c #808080",
"o	c #000000",
"O	c #ff0000",
"+	c #c0c0c0",
"@	c #808080",
"#	c #00ff00",
"                        ",
"                        ",
"   ...XXooooooo         ",
"   .......XXooo         ",
"   ...........o         ",
"   ...........o         ",
"   ...........o         ",
"   ...........o   O     ",
"   ...........o  OO     ",
"   ...........o OOO     ",
"   ...........oOOOOOOO  ",
"   ...........OOOOOOOO  ",
"   .......+X+.OOOOOOOO  ",
"   .......XoX.oOOOOOOO  ",
"   .......+X+.o OOO     ",
"   ...........o  OO     ",
"   ...........o   O     ",
"   ...........o         ",
"   ...........o         ",
"   ...........o         ",
"@@@@@##.......@@@@@@@@@@",
"@@@@@@@@@##...@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */
static char * FileImport_xpm[] = {
"24 24 10 1",
" 	c #ffffff",
".	c #000000",
"X	c #0000ff",
"o	c #008080",
"O	c #c0c0c0",
"+	c #808080",
"@	c #800000",
"#	c #ff0000",
"$	c #800080",
"%	c #000080",
"     .XXXXoOOO          ",
"    ..XXXXXXX++oOO      ",
"    .@#####$$XXXX+oOO   ",
"    @..XX$$#####$$$XXXO ",
"    +..%XXXXX$$$###$$XXX",
"..........XXXXXX$$$###$X",
".         .XXXXXXXXXX$##",
".          .XX.X%X%XX%X$",
". . .. .. . .X..XXX%XX%X",
".           .X...X%X%XX%",
". .. . . .. .%. ..X%X%%X",
".           ...  ..X%XX%",
". . .. .. . .     ..%%%%",
".           .      ..%%O",
". .. . .. . .     ..+XX ",
".           ...  .. OXX ",
". ... . ... .O. ..   oX ",
".           .O...X   OX ",
". . ... . . . ..XX      ",
".           . .%XX  OOOO",
". . . .. .. .  oXXOOOOOO",
".           .OOOXXOOOOOO",
".           .OOOXoOOOOOO",
".............OOOOOOOOOOO"};
/* XPM */
static char *filenewhull_xpm[] = {
"24 24 6 1",
"      c #C0C0C0",
"0     c #808080",
"1     c #000000",
"2     c #FFFFFF",
"3     c #800000",
"4     c #FF0000",
"                        ",
"             00112222211",
"         00111111112221 ",
"     00111111133442222  ",
" 00111111133444444 2    ",
"1111113344444433111     ",
"113344444433110 010     ",
"44444433110 2222222010  ",
"4433110 2222222222222201",
"1100 2222222222222222221",
"  1222222222222222222220",
" 0222222222222222222221 ",
" 1222222222222222222220 ",
"0222222222222222222221  ",
"1222222222222222222220  ",
"222222222222222222221   ",
"102222222222222222220   ",
"  010222222222222221    ",
"     010222222222220    ",
"        01022222221     ",
"           01022220     ",
"              0121      ",
"                        ",
"                        "};
/* XPM */
static char *fileopen_xpm[]={
"24 24 7 1",
"      c #DBD8D1",
"0     c #C0C0C0",
"1     c #808080",
"2     c #4D4D4D",
"3     c #000000",
"4     c #FFFF80",
"5     c #A6A64D",
"            01221       ",
"           12222211     ",
"          2210 01221  2 ",
"          22     221022 ",
" 12222221         12222 ",
"1322222231        02222 ",
"2214444122222221  22222 ",
"2244444412222222 222222 ",
"2244444444444422        ",
"2244444444444422        ",
"2244444444444422        ",
"2244444444444422        ",
"2244444422222222222222  ",
"2244444522222222222222  ",
"2244442255555555555552  ",
"2244452555555555555522  ",
"224422555555555555521   ",
"22452555555555555522    ",
"2222555555555555521     ",
"222255555555555522      ",
"22222222222222221       ",
"1222222222222221        ",
"                        ",
"                        "};
/* XPM */
static char *fileplot_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #808080",
"                        ",
"         ......         ",
"        X oo X..        ",
"        X oo XX.        ",
"        X oo X..        ",
" XXXXXXXX oo XX.X       ",
"........X oo X...       ",
".................       ",
".................       ",
".................       ",
".................       ",
"       XX.......X       ",
"        X oo X..        ",
"        X oo XX.        ",
"        X oo X..        ",
"         XXXXX.         ",
"         Xo  X.         ",
"         Xo  X.         ",
"     oooooXXX.ooooo     ",
"    o...... .....ooo    ",
"   oooooooo .oo.ooooo   ",
"  ooooooooo .o.ooooooo  ",
" oooooooooo ..ooooooooo ",
"oooooooooooooooooooooooo"};
/* XPM */
static char *fileprint_xpm[]={
"24 24 7 1",
"      c #C0C0C0",
"0     c #000000",
"1     c #FFFFFF",
"2     c #808080",
"3     c #D3D3D3",
"4     c #00FF00",
"5     c #FF0000",
"         0000000000     ",
"         0111111110     ",
"        0122222210      ",
"        0111111110      ",
"       0122222210       ",
"       0111111110       ",
"    00012222221000000   ",
"   0230111111110333200  ",
"  00001111111100002020  ",
" 023301111111103320210  ",
"2000000000000000202110  ",
"0111111111111111021110  ",
"01111111111111110111 0  ",
"0000000000000000011 00  ",
"011111111144155101 020  ",
"01111111114415510 0202  ",
"0111111111111111002 0   ",
"000000000000000002122   ",
"01111111111111112110    ",
"20111111111111112102    ",
" 201111111111111202     ",
"  0000000000000002      ",
"                        ",
"                        "};
/* XPM */
static char *filesave_xpm[]={
"24 24 5 1",
"      c #808080",
"0     c #000080",
"1     c #C0C0C0",
"2     c #D3D3D3",
"3     c #000000",
" 00000000000000000000 11",
"000000000000000000000011",
"000022222222222220330011",
"000022222222222220330011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000022222222222220000011",
"000000000000000000000011",
"000000000000000000000011",
"000011111111113333000011",
"000011333111113333000011",
"000011333111113333000011",
"000011333111113333000011",
"000011333111113333000011",
"000011333111113333000011",
"000011333111113333000011",
" 00011111111113333000011",
"1 00          3333000 11",
"111111111111111111111111"};
/* XPM */
static char *filewritedxf_xpm[] = {
"24 24 6 1",
" 	c #c0c0c0",
".	c #808000",
"X	c #ffff00",
"o	c #000000",
"O	c #ffffff",
"+	c #808080",
"         ......         ",
"         .XXXX.         ",
"      ....XXXX....      ",
"  ooooo.XXXXXXXX.ooooo  ",
"  oOOOOO.XXXXXX.OOOo+o  ",
"  oOOOo O.XXXX.OOOOo+o  ",
"  oOOOoo O.XX.OOOOOo+o  ",
"  oOOOoOo O..OOOOOOo+o  ",
"  oOOOoO o OOOOOOOOo+o  ",
"  oOOOoOO o OOOOOOOo+o  ",
"  oOOOoOoO o OOOOOOo+o  ",
"  oOOOoOooO o OOOOOo+o  ",
"  oOOOoOo oO o OOOOo+o  ",
"  oOOOoOoO oO o OOOooo  ",
"  oOOOoOoooooO o OOo oo ",
"  oOOOoOOOOOOOO o Oo +o ",
" ooooooooooooooooooo +oo",
" oOXOOXOXOXOXOXOXOXo ++o",
" o.................o ++o",
" ooooooooooooooooooo +oo",
"  o                o +o ",
"  oooooooooooooooooo oo ",
"  o++++++++++++++++ooo  ",
"  oooooooooooooooooo    "};
/* XPM */
static char *helphull_xpm[] = {
"24 24 6 1",
" 	c #c0c0c0",
".	c #404040",
"X	c #ff0000",
"o	c #800000",
"O	c #0000ff",
"+	c #000000",
"                        ",
"         ......         ",
"       ..........       ",
"      ...      ...      ",
"      ..        ...     ",
"     ..   XXoo   ..     ",
"     ..XXXXXooooo..     ",
"   XX..XXXXXooooo..ooo  ",
"  XXXXXXXXXXooooo..ooo  ",
"  XXXXXXXXXXoooo ..ooo  ",
"  XXXXXXXXXXoooo.. ooo  ",
"  XXXXXXXXXXooo...oooo  ",
"   XXXXXXXXXo ...oooo   ",
"   XXXXXXXXX ...ooooo   ",
"   XXXXXXXX .. oooooo   ",
"   XXXXXXXo.. ooooooo   ",
"OOOOXXXXooX..o++ooooOOOO",
"OOOOXXooXXX..ooo++ooOOOO",
" OOOooXXXXX..ooooo++OOO ",
"  OOOOOXXXXXoooooOOOOO  ",
"   OOOOOOOX..oOOOOOOO   ",
"     OOOOO....OOOOOO    ",
"       OOO....OOOO      ",
"          O..OO         "};
/* XPM */
static char *help_xpm[] = {
"24 24 3 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"                        ",
"        ..XXXX..        ",
"      .XXXXXXXXXX.      ",
"     .XXXXXXXXXXXX.     ",
"     XXXX..  ..XXXX     ",
"    .XXX.      .XXX.    ",
"    XXX.        .XXX    ",
"    XXX.        .XXX    ",
"                .XXX    ",
"               .XXX.    ",
"              .XXXX     ",
"             .XXXX.     ",
"            .XXXX.      ",
"            XXXX.       ",
"           .XXX.        ",
"           XXX.         ",
"           XXX.         ",
"           XXX          ",
"           XXX          ",
"                        ",
"                        ",
"           XXX          ",
"           XXX          ",
"           XXX          "};
/* XPM */
static char *hullstat_xpm[] = {
"24 24 9 1",
" 	c #c0c0c0",
".	c #800000",
"X	c #000080",
"o	c #ffffff",
"O	c #808080",
"+	c #008080",
"@	c #ff0000",
"#	c #00ffff",
"$	c #0000ff",
"   .XXXXXXXXXXXXXXXXXXXo",
" .XXooooooooooooooooOOXo",
".XoooooooooooooooooOOoXo",
"X.XXXXXXXXXXXXXXXXXoOoXo",
"X.XX+XXXXXXXX@XXXXXOooXo",
"X.XX#++XXXXX@@@XXXXoooXo",
"XXX+###++XX@@@@@XXXOOoXo",
"X.X+#####X@@@@@@@XXoooXo",
"X.X######@@@@@@@@@XoOoXo",
"X.+#######$#@@@XXXXoooXo",
"X.+#######$#@@@+XXXOOoXo",
"X.$$$$$$$$##@@@+#XXoOoXo",
"X.X######$$#@@@#+#+OooXo",
"X.X#####$##$#+#+#++oooXo",
"X.XX####$###$#+#++XoOoXo",
"X.XX##@@@####$#++XXOOoXo",
"X.XXX#@@@#####$+XXXOooXo",
"XXXXXX@@@######XXXXoOoXo",
"X.XXXX@@@XXXXXXXXXXOooXo",
"X.XX@@@@@@@XXXXXXXXooOXo",
"X.XXX@@@@@XXXXXXXXXoO  o",
"X.XXXX@@@XXXXXXXXXXO   o",
"XXXXXXX@XXXXXXXXXX.    o",
"X.XXX....XX....X...    o"};
/* XPM */
static char *iconpilotboat_xpm[] = {
"24 24 8 1",
" 	c #00ffff",
".	c #808080",
"X	c #c0c0c0",
"o	c #000000",
"O	c #ff0000",
"+	c #800000",
"@	c #008080",
"#	c #808080",
"                        ",
"                        ",
"        .               ",
"       ...              ",
"        .               ",
"        .XXX            ",
"        . X             ",
"        . o             ",
"     O.+...+.+          ",
"     +.O......+X.XX.    ",
"    +O.+....+.. .  .    ",
"@@@@+OO+OO+OO+.oo.XXXXo@",
"@@@####O++O+oo.XXX..o.XX",
"@@#XX####oo.XXX..ooooo.#",
"#X#####XX#X##oooooooooX#",
"##@@X#X##XXX######XXo.##",
"@@@@@@###XXXXXXX#X##.X##",
"@#@@@@@@@@@@###@@@@@@@@@",
"@@#@@@@@@##@@@@#@@@@@@@@",
"@@@@@@.....#@@@@@@###@@@",
"@@@@@@##@@@@@@@@@@@@@@@@",
"@@@@@@@@@@##@#@@@@#@@#@@",
"@..@@@@@@@@@#@@@@@@##@@@",
"@@@@@@@@@@@@@@@@#@@@@@@@"};
/* XPM */
static char *iconworkboat_xpm[] = {
"24 24 7 1",
" 	c #00ffff",
".	c #000000",
"X	c #ff0000",
"o	c #808080",
"O	c #008080",
"+	c #c0c0c0",
"@	c #808080",
"                        ",
"                        ",
"      ..   XXXXX.oo     ",
"       oooooooooooooo   ",
"OOOOOOO++++++++++++++OOO",
"OOOOOOOo@@o@@o@@@o@@oOOO",
"OOOOOOOo@@o@@o@@@o@@oOOO",
"OOOOOOOo@++@@o@@++@+oOOO",
"OOOOOOOo@++@@o@@++@o+OOO",
"OOOOOOOoooooo+oo+o+o O O",
" O O OO.@+ooooooo+o+OOOO",
"O+........@oo+oo+o.. OO ",
".+oOOOO.............O  O",
"..+o+OO.....@++oooooo+O ",
".@..+o++@++oo++@.....+oO",
".@@..+ooo++.......+...@ ",
"O@.@o++o+.......+.+.+.+O",
"oo+.@.@+ooo++@..@+++@+o@",
"OoO.@.@...@+oooooooooo@.",
" OO+@.@.................",
"OooO+.@................o",
" O OO+@....oo....oo.oo.o",
"oooooooooooooo..oooooooo",
"Oooooooooooooooooooooooo"};
/* XPM */
static char *iconyachthull_xpm[] = {
"24 24 10 1",
" 	c #ffffff",
".	c #000000",
"X	c #0000ff",
"o	c #008080",
"O	c #c0c0c0",
"+	c #808080",
"@	c #800000",
"#	c #ff0000",
"$	c #800080",
"%	c #000080",
" .XXXXoOOO              ",
"..XXXXXXX++oOO          ",
".@#####$$XXXX+oOO       ",
"@..XX$$#####$$$XXXO     ",
"+..%XXXXX$$$###$$XXXO   ",
"O..XXXXXXXXX$$$###$XXO  ",
" +.XXXXXXXXXXXXXX$###$O ",
" O.%XX%X%X%X%X%XX%X$##$ ",
"  +X%XXXXXXXXXX%XX%XX$# ",
"  O.%X%X%X%X%X%X%XX%X%% ",
"   O.%%%X%X%X%X%X%%X%%o ",
"    OX%X%X%X%X%X%XX%%%O ",
"     O%%%%%%%%%X%%%%+O  ",
"       O%%%%%%%%%%%O    ",
"        Oo%%%%%++XX     ",
"         o%XXX  OXX     ",
"         O%XXX   oX     ",
"         Oo%XX   OX     ",
"          o%XX          ",
"          O%XX  OOOOOO  ",
"           oXXOOOOOOOO  ",
"         OOOXXOOOOOOOOO ",
"       OOOOOXoOOOOOOOOO ",
"     OOOOOOOOOOOOOOOOO  "};
/* XPM */
static char *plateevaluate_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"o	c #ff0000",
"O	c #808080",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"   ..XXXXXXXXXX...      ",
"XXX. o OOOoOO  oXXXX..  ",
"oOOOOoOOOOoOOOOoOO  oXXX",
"oOOOOOoOOOoOOOOoOOOoOOOX",
" oOOOOoOOOoOOOOoOOOoOO X",
" oOOOOoOOOOoOOoOOOoOOO X",
"  oOOOOoOOOoOOoOOoOOOO..",
"  oOOOOoOOOoOOoOOoOOOoX.",
"   o  ..XXXXXXXX..  oOX ",
"   XXXX..      ..XXXXX. ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *plateundoruling_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #0000ff",
"o	c #ff0000",
"                        ",
"                        ",
".....                   ",
"  X  .....              ",
"  X     X ...           ",
"   X    X   ....        ",
"   X    X   .X. ..      ",
"   X    Xoo .X.ooX..    ",
"   X    Xooo.XoooX  ..  ",
"    X   X oooooo X   X. ",
"    X   X  oooo X   X  .",
"    X   X  oooo X   X   ",
"     X  X ooooooX  X    ",
"     X  Xooo. ooo  X   X",
"  ..... XooX.  oo X   X ",
"       ......   X X  X  ",
"             ....X  X   ",
"                 ..X    ",
"                    ... ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *runcad_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #ff0000",
"X	c #000000",
"o	c #808080",
"O	c #808080",
"+	c #ffff00",
"@	c #808000",
"                        ",
"                        ",
"                        ",
".... . XXXXXXXXXXXXXXXXX",
"       XoooooooooooooXOX",
"... . OXoX ooooooooo XOX",
"      X XXOoooooooooXOXO",
".. .. XoXOX ooooooooXOX ",
"     OX X OX oooooo XOX ",
".. . X XOo XOooooooXOXO ",
"     XoX Xo X oooooXOX  ",
". . OX XoXXoOX ooo XOX  ",
"    X XOX Xo XOoooXOXO  ",
". . XoX Xo Xo X ooXXX   ",
"   OX XoXXXXXoOX  X XX  ",
".  XoXoooooooo X X OX   ",
"  XXXXXXXXXXXXXXXX OXX  ",
"  Xo++o+o+o+o+o+oX OOX  ",
" X@@@@@@@@@@@@@@X OOX   ",
" XXXXXXXXXXXXXXXX OXX   ",
"  X             X OX    ",
" XXXXXXXXXXXXXXX XX     ",
" XOOOOOOOOOOOOOXXX      ",
" XXXXXXXXXXXXXXX        "};
/* XPM */
static char *runcalculator_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #00ffff",
"X	c #008080",
"o	c #000000",
"O	c #808080",
"+	c #808080",
"   .................    ",
"  .XXXXXXXXXXXXXXXXXX   ",
" .XXoooooooooooooooXX.  ",
" .XXoOOooOooOooOOoOXX.  ",
" .XXoOOOoOooOooOooOXX.  ",
" .XXoOOOOOOOOOOOOOOXX.  ",
" .XXXXXXXXXXXXXXXXXXX.  ",
" .XXO oXO oXO oXO oXX.  ",
" .XX  oX  oX  oX  oXX.  ",
" .XXoooXoooXoooXoooXX.  ",
" .XXXXXXXXXXXXXXXXXXX.  ",
" .XXO oXO oXO oXO oXX.  ",
" .XX  oX  oX  oX  oXX.  ",
" .XXoooXoooXoooXoooXX.  ",
" .XXXXXXXXXXXXXXXXXXX.  ",
" .XXO oXO oXO oXO oXX.  ",
" .XX  oX  oX  oX  oXX.  ",
" .XXoooXoooXoooXoooXX.  ",
" .XXXXXXXXXXXXXXXXXXX.  ",
" .XXO oXO oXO oXO oXX.  ",
" .XX  oX  oX  oX  oXX.  ",
" .XXoooXoooXoooXoooXX.  ",
"  XXXXXXXXXXXXXXXXXX+   ",
"   +++++++++++++++++    "};
/* XPM */
static char *rundos_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #000000",
"o	c #808080",
"                        ",
"                        ",
"                        ",
"                        ",
"    .XXXX.    .X        ",
"   oX....Xo   .X    .   ",
"  .X.    .X.   X.   X.  ",
"  Xo      oo X oo   .X  ",
" .X.      .X X .X    X. ",
" oX.      .X   .X    .X.",
" XX             X.    XX",
" XX             Xo    .X",
" XX             oX    XX",
" oX.      .X    .X   .X ",
" .X.      .X X   X.  X. ",
"  Xo      oo X   Xo .X  ",
"  .X.    .X.     oX X.  ",
"   oX....Xo      .X..   ",
"    .XXXX.        X.    ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *runeditor_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #00ffff",
"O	c #c0c0c0",
"+	c #008080",
"        .X .X .X .X .X  ",
"       . .. .. .. .. .  ",
"      .o.oO.Oo.oO.O+... ",
"      .OoOoOoOoOoO+.OX. ",
"     .OoOoOoOoOoOo+.OX. ",
"     .oOoOoOoOoOo+.OOX. ",
"    .oOoO....oOoO+.OOX. ",
"    .OoOoOoOoOoO+.OOOX. ",
"   .OoOo....OoOo+.OOOX. ",
"   .oOoOoOoOoOo+.XXXOX. ",
"  .oOoOoOoOoOoO+.OO OX. ",
"  .OoOoOoOoOoOo.O   OX. ",
" .OoOoOoOoOoOoX.XXXXOX. ",
" .oOoOoOoOoOoO.O    OX. ",
".oOoOoOoOoOoOo.O    OX. ",
".+++++++++++X.XXXXXXOX. ",
" ............OO     OX. ",
"      .OOOOOOOO     OX. ",
"      .XXXXXXXXXXXXXOX. ",
"      .OOOOO        OX. ",
"      .            OOX. ",
"      ..OOOOOOOOOOOOXX. ",
"       ..XXXXXXXXXXXX.. ",
"        ..............  "};
/* XPM */
static char *runfilemanager_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #808080",
"X	c #ffff00",
"o	c #808000",
"O	c #808080",
"+	c #000000",
"     .X X X X X X X X.  ",
"    .X X X X X X X X..  ",
"   .X X X X X X X X.o.  ",
"  .OOOOOOOOOOOOOOO.oo.  ",
"  . X X X X X X X .oo.  ",
"  .ooooooooooooo+X.oo.  ",
"  .oOOOOOOOOOOOO+ .oo.  ",
"  .oOX X X X X X+X.oo.  ",
"  .oO X++++++ X + .oo.  ",
"  .oOX +oooo+X X+X.oo.  ",
"  .oO X+oooo+ X + .oo.  ",
"  .oO X X X X X + .oo.  ",
"  .oOX X X X X X+X.oo.  ",
"  .++++++++++++++ .oo.  ",
"  .ooooooooooooo+ .oo.  ",
"  .oOOOOOOOOOOOO+X.oo.  ",
"  .oO X X X X X + .oo.  ",
"  .oOX ++++++X X+X.oo.  ",
"  .oO X+oooo+ X + .oo.  ",
"  .oOX +oooo+X X+X.oo.  ",
"  .oO XOOOOOO X + .oo.  ",
"  .oO X X X X X + .o.   ",
"  .++++++++++++++X..    ",
"  .................     "};
/* XPM */
static char *smalso_xpm[] = {
"24 24 3 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"                        ",
"        ..XXX..         ",
"       XXXXXXXXX        ",
"      XXXXXXXXXXX       ",
"     .XXXX   XXXX.      ",
"     XXXX     XXXX      ",
"     XXXX     XXXX      ",
"     .XXXX   XXXX.      ",
"      XXXXX XXXXX       ",
"       XXXXXXXXX        ",
"        XXXXXXX         ",
"      .XXXXXXX          ",
"     XXXXXXXXX.         ",
"    XXXXX.XXXXX.  XXX   ",
"   .XXXX.  XXXXX.XXXX   ",
"   XXXX.    XXXXXXXXX   ",
"   XXXX      XXXXXXX.   ",
"   XXXX       XXXXX.    ",
"   .XXX.      XXXXXX    ",
"    XXXX.   .XXXXXXXX.  ",
"    XXXXXXXXXXXXXXXXXXX ",
"     XXXXXXXXXXX  .XXX  ",
"       ..XXX..      X   ",
"                        "};
/* XPM */
static char *smcurve_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #ff0000",
"X	c #000000",
"o	c #808080",
"O	c #c0c0c0",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"      ...               ",
"     .....              ",
"...........XoO          ",
"...........XXXXO        ",
"...........XXXXXo       ",
"     .....   oXXXX      ",
"      ...     OoXXX     ",
"                oXXX    ",
"                 oXXo   ",
"                  oXX   ",
"                   XXX  ",
"                   OXXO ",
"                    XXX ",
"                     X  ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *smflexibility_xpm[] = {
"24 24 3 1",
" 	c #ffffff",
".	c #000000",
"X	c #ff0000",
"     .           .      ",
"     .     .     .    . ",
".     .    .    .    .  ",
" .    .    .    .   .   ",
"  .    .   .   .   .    ",
"   .   .   .   .  .     ",
"    .   .  .  .  .      ",
"     .          .       ",
"         XXXXX          ",
"       XXXXXXXXX        ",
"      XXXXXXXXXXX       ",
"     XXXXX   XXXXX      ",
"     XXX       XXX      ",
"    XXX         XXX     ",
"    XXX         XXX     ",
"   XXX           XXX    ",
"   XXX           XXX    ",
"   XXX           XXX    ",
"  XXX             XXX   ",
"  XXX             XXX   ",
"  XXX             XXX   ",
" XXX               XXX  ",
" XXX               XXX  ",
"                        "};
/* XPM */
static char *smignore_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #ff0000",
"O	c #808080",
"+	c #ffff00",
"        ..X   X..       ",
"        X..X X..X       ",
"         X..X..X        ",
"          X...X         ",
"          X...X         ",
"         X..X..X        ",
"        X..X.X..X       ",
"        ..X . X..       ",
"            .           ",
"   ...................  ",
"   .     .     .  .  .  ",
"  ...   ...   ......... ",
"  X.X   X.X   X.XX.XX.X ",
"   .   oo.ooo  .  .  .  ",
"    oooOO+OO.oo         ",
"  ooOO.OO+OO.OOoo       ",
" oO+OO.OO+OO.OO+Ooo     ",
"oOO+OO.OO+OO.OO+OO+o    ",
".OO+OO.OO+OO.OO+OO+Oo   ",
".OO+OO.OO+OO.OO+OO+OOo  ",
".OO+OO.OO+OO.OO+OO+OO+o ",
".OO+OO.OO+OO.OO+OO+OO+Oo",
"........................",
"                        "};
/* XPM */
static char *smmaster_xpm[] = {
"24 24 7 1",
" 	c #ffffff",
".	c #000000",
"X	c #800000",
"o	c #808080",
"O	c #ff0000",
"+	c #808080",
"@	c #ffff00",
"               ...      ",
"              .X.o      ",
"      ...o   .XO.       ",
"       .... ..O.o       ",
"       o.O...O..        ",
"        ..OOOO.o        ",
"         ..OO..         ",
"          ....          ",
"           o.           ",
" ...................... ",
" .    .     .         . ",
"...  ...   ...       ...",
"o.o  o.o   o.o       o.o",
" .    .OOOOO.         . ",
"     OO++@++OO          ",
"   OO+.++@++.+OO        ",
"  O+@+.++@++.++@OO      ",
" O++@+.++@++.++@+@O     ",
" .++@+.++@++.++@+@+O    ",
" .++@+.++@++.++@+@++O   ",
" .++@+.++@++.++@+@++@O  ",
" .++@+.++@++.++@+@++@+O ",
" ...................... ",
"                        "};
/* XPM */
static char *smpull_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #ff0000",
"X	c #000000",
"o	c #c0c0c0",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
".                       ",
"...                   ..",
".....              .....",
"   ....         ....... ",
"     ....    ......     ",
"       .........        ",
"         ....           ",
"           XXXXXXXXXXX  ",
"           X       oX   ",
"           X      oX    ",
"           X     oX     ",
"           X     oX     ",
"           X      oX    ",
"           X  oo   oX   ",
"           X oXXo   oX  ",
"           XoX  Xo   oX ",
"           XX    Xo oX  ",
"           X      XoX   ",
"                   X    "};
/* XPM */
static char *smsmooth_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"O	c #ff0000",
"                        ",
"                        ",
"                        ",
"                        ",
"            ..XXooo     ",
"       ..XXooooooooo    ",
"   .XXoooooooXX.oooo    ",
"  oooooooXX.    ooooo   ",
"  oooXX.        ooooo   ",
"  oo.           oooo    ",
"  oo       ..XXooooo    ",
"  ooX ..XXooooooooo     ",
"  oooooooooooXX...X     ",
"  ooooooXX...... ..X    ",
"  X. ............ ..X   ",
" X. .............. ..X  ",
" X. ............... ..X ",
" X. ................ .X ",
" oooooooooooooooooooooo ",
"         OOOOOO         ",
"   OOOOOOOOOOOOOOOOOO   ",
"OOOOOOOOO      OOOOOOOOO",
"OOO                  OOO",
"                        "};
/* XPM */
static char *smvalue_xpm[] = {
"24 24 2 1",
" 	c #ffffff",
".	c #000000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"   ..................   ",
"   ..................   ",
"                        ",
"                        ",
"                        ",
"                        ",
"   ..................   ",
"   ..................   ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *staticsbalancehull_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #ffff00",
"X	c #ff0000",
"o	c #800000",
"O	c #00ffff",
"+	c #0000ff",
"                        ",
"                        ",
"                        ",
"             ..         ",
"     XXX    ....        ",
"     XXXXXX......       ",
"     XXXXX........      ",
"    XXXXXXXXX...        ",
"    XXXXXXXXX...o       ",
"    XXXXXXXXX...oo      ",
"   XXXXXXXXXo...ooo     ",
"   XXXXXXXXXo...oooo    ",
"   XXXXXXXXoo...ooooo   ",
"   XXXXXXXXoo...oooooo  ",
"    XXXXXXOOO...ooooo   ",
"     XXXXoOOO...oooo    ",
"++++++XXXoOOOoooooo+++++",
"+++++++XooOOOooooo++++++",
" +++++++ooOOOoooo++++++ ",
"  ++++++OOOOOOO+++++++  ",
"   ++++++OOOOO+++++++   ",
"     +++++OOO+++++++    ",
"       ++++O++++++      ",
"          +++++         "};
/* XPM */
static char *staticsplotvariables_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #0000ff",
"X	c #ffffff",
"o	c #000000",
"O	c #ff0000",
"   .....................",
"   .XXXXXXXXXXXXXXXXXXX.",
"   .XXXXXXXXXXXXXXXXXXX.",
"   .XXXXXXXXXXXXXXXXXXX.",
"   ..XXXXXXXXXXXXXXXXXX.",
"   .XXXXXXXXXXXXXXXXXXX.",
"ooo.XXXXXXXXXXXXXXXXXXX.",
"o  .XXXXXXXXXOOOXXXXXXX.",
"o o..XXXXXXOOXXXOOXXXXX.",
"ooo.XXXXXXOXXXXXXXOXXXX.",
"   .XXXXXOXXXXXXXXXOXXX.",
"ooo.XXXXOXXXXXXXXXXXOXX.",
"  o..XXOXXXXXXXXXXXXXOX.",
" o .XXXOXXXXXXXXXXXXXXO.",
"ooo.XXOXXXXXXXXXXXXXXXX.",
"   .XXOXXXXXXXXXXXXXXXX.",
"   ..OXXXXXXXXXXXXXXXXX.",
"   .XOXXXXXXXXXXXXXXXXX.",
"   .OXXXXXXXXXXXXXXXXXX.",
"   .OXX.XXX.XXX.XXX.XXX.",
"   .....................",
"      o o ooo ooo o     ",
"      ooo oo  oo  o     ",
"      o o ooo ooo ooo   "};
/* XPM */
static char *staticssettings_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #000000",
"X	c #808080",
"o	c #800000",
"O	c #ff0000",
"+	c #0000ff",
"                        ",
".      ....   ....      ",
".     .X   . .X  X.     ",
".     .      .          ",
".     .      .          ",
".     .      .  ...     ",
".     .      .    .     ",
".o    .o  oooo  OooooO  ",
".oO   .o oX. .o o.. Oo  ",
"..o.. o..o.   ..o .     ",
"  o   o  o      o       ",
"  oO Oo  o      o  ooo  ",
"  Oo oO  o      o    o  ",
"   o o   o      o    o  ",
"   +oO  +oO  Oo oO Ooo +",
"   +o   +OooooO OoooOo +",
"   +    +              +",
"   +    +   +++   +++  +",
"   ++++++  +   + +   + +",
"   +    +  +++++ +++++ +",
"   +    +  +     +     +",
"   +    +  +   + +   + +",
"   +    +   +++   +++  +",
"                        "};
/* XPM */
static char *staticstabularoutput_xpm[] = {
"24 24 2 1",
" 	c #000000",
".	c #ffffff",
" . ....... ..   .   .. .",
" . .  .  . .. ..... .. .",
"   .  .  . .. . .. ...  ",
" . .  .  . ..   .   .. .",
"........................",
". ..   ....... ...   ...",
". .. . ....... ..... ...",
". .. . ....... ... .....",
". ..   ..... . ...   ...",
"........................",
"   .   .......   .   ...",
".. . . ......... ... ...",
". .. . ........ ... ....",
"   .   ..... .   .   ...",
"........................",
"   .   .......   .. ....",
".  . . ........  .. ....",
".  . . ........  .. ....",
"   .   ..... .   .. ....",
"........................",
" . .   .......   .   ...",
" . . . ........  .   ...",
"   . . ........  ... ...",
".. .   ..... .   .   ..."};
/* XPM */
static char *tankaddtank_xpm[] = {
"24 24 6 1",
" 	c #000000",
".	c #808080",
"X	c #800000",
"o	c #808080",
"O	c #808000",
"+	c #ffffff",
"                        ",
"....................... ",
"........XXXXXXXXXXXXX.. ",
"........X...........X. o",
"........X..........OX. o",
"........X..........XO. +",
"........X..........XO+ +",
"........X..........X.o +",
"........X..........X. o+",
"........X.........OX. o+",
"........X.........XO. ++",
"........X.........XO+ ++",
"........X.........X.o ++",
"........X........OX. o++",
"........X........OX. o++",
"........X.......OX.+ +++",
"........X......OX.+ o+++",
"........X..OOXXX.+ o++++",
"........XXXXXO.+  o+++++",
"............+o  oo++++++",
"........+o    o+++++++++",
"...++o    oo++++++++++++",
"      o+++++++++++++++++",
"++++++++++++++++++++++++"};
/* XPM */
static char *tankproperties_xpm[] = {
"24 24 9 1",
" 	c #000000",
".	c #ff0000",
"X	c #808080",
"o	c #0000ff",
"O	c #800000",
"+	c #808000",
"@	c #c0c0c0",
"#	c #808080",
"$	c #00ffff",
"  .                     ",
"XX.XXXXXXXXXXXXXXXXXXXX ",
"XX.XoXoXXOOOOOOOOOOOOOX ",
"XX.ooXooXOXXXXXXXXXXXOX ",
"XXoooXoooOXXXXXXXXXX+OX ",
"XoooooooooXXXXXXXXXXO+@ ",
"oooooooooooXXXXXXXXXO+# ",
"XoooooooooXXXXXXXXXXOX##",
"XXoooXoooO$$$..$$$$$OX #",
"XX.ooXooXO$$....$$$+OX @",
"XXXXoXoXXO$......$$O+X @",
"XX.XXXXXXO........$O+@ @",
"XXX$ooo$XO$$$..$$$$OX# @",
"XX.o$X$oXO$$$..$$$+OX #@",
"XX.XXXXoXO$$$..$$$+OX #@",
"XX.XXX$oXO$$$..$$+OX@ @@",
"XXXXX$o$XO$$$..$+OX@ #@@",
"XX.XXo$XXO$$++OOOX@ #@@@",
"XXXXXoXXXOOOOO+X@  #@@@@",
"XX.XXXXXXXXXX@#  ##@@@@@",
"XX.XXoXXX@#    #@@@@@@@@",
"XX.X@@#    ##@@@@@@@@@@@",
"  .    #@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@"};
/* XPM */
static char *tankstatics_xpm[] = {
"24 24 8 1",
" 	c #000000",
".	c #ff0000",
"X	c #808080",
"o	c #800000",
"O	c #808000",
"+	c #c0c0c0",
"@	c #808080",
"#	c #00ffff",
"  .                     ",
"XX.XXXXXXXXXXXXXXXXXXXX ",
"XX.XXXXXXoooooooooooooX ",
"XX.XXXXXXoXXXXXXXXXXXoX ",
"XX.XXXXXXoXXXXXXXXXXOoX ",
"XX.XXXXXXoXXXXXXXXXXoO+ ",
"XX XXXXXXoXXXX XXXXXoO@ ",
"X               XXXXoX@@",
"XX XXXXXXo#### #####oX @",
"XX.XXXXXXo#########OoX +",
"XXXXXXXXXo##.....##oOX +",
"XX.XXXXXXo##.....##oO+ +",
"XXXXXXXXXo##.....##oX@ +",
"XX.XXXXXXo##.....#OoX @+",
"XX.XXXXXXo##.....#OoX @+",
"XX.XXXXX............. ++",
"XXXXXXXXX........... @++",
"XX.XXXXXXo......... @+++",
"XXXXXXXXXoo....... @++++",
"XX.XXXXXXXXX.....@@+++++",
"XX.XXXXXX+@  ...++++++++",
"XX.X++@    @@+.+++++++++",
"  .    @++++++++++++++++",
"++++++++++++++++++++++++"};
/* XPM */
static char *viewallorthogonal_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #000000",
"X	c #ff0000",
"o	c #c0c0c0",
"O	c #808080",
"                        ",
"                        ",
"                        ",
"                        ",
".........  .............",
". X . X .  .  X  X  X  .",
". X . X .  .  X  X  X oO",
"oO X.X Oo  .  X  X  X .o",
" .o . o.    .OOo X  oOo ",
"  O...O       oO.....o  ",
"                        ",
"                        ",
"                        ",
"                        ",
"             oOO...Oo   ",
"            .Ooo XooO.  ",
"           .  X  X  X . ",
"           .  X  X  X  .",
"           .............",
"           .  X  X  X  .",
"           .  X  X  X . ",
"            .Ooo XooO.  ",
"             oOO...Oo   ",
"                        "};
/* XPM */
static char *viewbodyplan_xpm[] = {
"24 24 4 1",
" 	c #ffffff",
".	c #000000",
"X	c #c0c0c0",
"o	c #800000",
"                        ",
"                        ",
"         ......         ",
"     ....XX..XX....     ",
"  ...XXoXXX..XXXoXX...  ",
" .oXoXXoXXX..XXXoXXoXo. ",
".XoXoXXoXXX..XXXoXXoXoX.",
".XoXoXXXoXX..XXoXXXoXoX.",
".XoXXoXXoXX..XXoXXoXXoX.",
".XXoXoXXoXX..XXoXXoXoXX.",
" .XoXXoXXoX..XoXXoXXoX. ",
" .XoXXoXXoX..XoXXoXXoX. ",
" .XXoXXoX......XoXXoXX. ",
"  .XoXX..Xo..oX..XXoX.  ",
"  .XX..XoXX..XXoX..XX.  ",
"   ..oXXXoX..XoXXXo..   ",
"   .XXoXXXo..oXXXoXX.   ",
"    .XXoXXX..XXXoXX.    ",
"     .XXoXX..XXoXX.     ",
"      ..Xoo..ooX..      ",
"        ........        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *viewfullpersp_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #00ffff",
"X	c #008080",
"o	c #0000ff",
"O	c #c0c0c0",
"+	c #ff0000",
"                        ",
"                        ",
"                        ",
"             .Xooooooo. ",
"          .XoooXXOOOoXo.",
"        .ooXXOOOOOOXoOXo",
"      .o+XOOOOOOOOOXoOO+",
"    .+oO+OOOOOOOOOOoXOO+",
"   .o+OO+OOOOOOOOOOoXOO+",
"   oX+OO+OOOOOOOOOXoOOO+",
"   +O+OOO+OOOOOOOOXoOO+ ",
"  o+O+OOO+OOOOOOOOoXOO+ ",
" .o+O+OOO+OOOOOOOOoXOO+ ",
" o++OO+OOO+OOOOOOXoOO+  ",
" o+O+O+OOO+OOOOOOXoOO+  ",
" o+O+O+OOOO+OOOOOoXO+   ",
" .+O+OO+OOOO+OOOXoO+    ",
" .+O+OO+OOOOO+OOoO+     ",
"  o+O+OO++OOOO+o++      ",
"  .+OO+OOO++oooOO       ",
"   o++++oooo..          ",
"    .ooo.               ",
"                        ",
"                        "};
/* XPM */
static char *viewlinesmooth_xpm[] = {
"24 24 6 1",
" 	c #c0c0c0",
".	c #000000",
"X	c #808080",
"o	c #808080",
"O	c #800000",
"+	c #0000ff",
"                        ",
"                    .   ",
"                   .X.  ",
"               .  .XXX. ",
"               ...XXX.  ",
"               .XXXX.   ",
"               .XXX.    ",
"               .XXX.    ",
"     oo....O..o......   ",
"  o....o   O o...o      ",
"..oO   O   O   O ..o    ",
".  O   O   O   O  o..   ",
".  O   O   O   O   Oo.  ",
".  O   O   O   O   O  . ",
".  O   O   O   O   O   .",
"+ + +++ + +++ + +++ + ++",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *viewplan_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"O	c #800000",
"+	c #ff0000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"      .XoooooooX.       ",
"  .XooooO...OXXooo.     ",
"ooooO...O...O...O.oo.   ",
"o...O...O...O...O...o.  ",
"o...O...O...O...O...Oo. ",
"o...O...O...O...O...O.o ",
"o...O...O...O...O...O..o",
"o+++O.+.O+++O+.+O+.+O+++",
"o...O...O...O...O...O..o",
"o...O...O...O...O...O.o ",
"o...O...O...O...O...Oo. ",
"o...O...O...O...O...o.  ",
"ooooO...O...O...O.oo.   ",
"  .XoooXO...OXXooo.     ",
"      .XoooooooX.       ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *viewportpersp_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #0000ff",
"X	c #008080",
"o	c #00ffff",
"O	c #c0c0c0",
"+	c #ff0000",
"                        ",
".......XXoo             ",
".OOOXXX....Xo           ",
".OOOOOOOOXX...Xo        ",
".XOOOOOOOOOO+X..Xo      ",
".XOOOOOOOOOO+OOX..X     ",
"X.OOOOOOOOOO+OOOO+.X    ",
"X.OOOOOOOOO+OOOOO+X.X   ",
" .OOOOOOOOO+OOOOO+OX.X  ",
" .XOOOOOOOO+OOOOO+OO+.  ",
" .XOOOOOOO+OOOOOO+OO+.X ",
" X.OOOOOOO+OOOOO+OOO+O. ",
" X.OOOOOO+OOOOOO+OOO+O.X",
"  .XOOOOO+OOOOOO+OOO+O+.",
"  .XOOOO+OOOOOO+OOO+OO+.",
"  X.OOO+OOOOOOO+OOO+OO+.",
"   .X++OOOOOOO+OOO+OO+.X",
"    .OOOOOOOO+OOOO+OO+.X",
"     .OOOOOO+OOOO+OOO+. ",
"      ..++++OOOO+OOO+.X ",
"       X...X++++OOO+X.  ",
"          X....X+++..X  ",
"             XX....X    ",
"                        "};
/* XPM */
static char *viewposition_xpm[] = {
"24 24 5 1",
" 	c #c0c0c0",
".	c #000000",
"X	c #808080",
"o	c #808080",
"O	c #00ffff",
"                        ",
"                        ",
"           .   .        ",
"       .   .   .        ",
"        .  .. .    .    ",
"    .    XX...X   .     ",
"     . X..oooooX..    . ",
"  .   ..ooOOOOooo.. ..  ",
"   . .oooOOOOOOoooX.    ",
" .  .XooOOO..OOOoooX... ",
"  . .oooOO....OOoooo.   ",
"   .ooooOO....OOooooo.  ",
" ..oooooOOO..OOOoooo..  ",
"   ..XoooOOOOOOoooo.    ",
"     ..XooOOOOoooX.     ",
"       ..Xoooo X..      ",
"         XX....X        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *viewprofile_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"O	c #800000",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"           ..XXooooooooo",
"    ..XXoooooooOX..O...o",
"ooooooXX..O....O...O...o",
"o....O....O....O...O..oX",
"o....O....O....O...O.oo.",
"o....O....O....O..ooooX ",
"oooooo....O....ooo.O.o. ",
"o....OoooooooooO...OoX  ",
"o....O....O....O...Xo.  ",
" ooooXX...O....O.ooo.   ",
"   ..XXoooooooooooX.    ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "};
/* XPM */
static char *viewshaded_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #c0c0c0",
"X	c #808080",
"o	c #000000",
"O	c #008080",
"                        ",
"                        ",
"                        ",
"              .......X. ",
"          .....     oXX.",
"        ....        XXXX",
"      ....         .oXXX",
"     .. . .  . .   .XXXX",
"    .. . . .       XXXXX",
"   .. . . . . . .  oXXX.",
"   . . . . . .    .XXXX.",
"  ..... . . . . . .ooXX ",
"  .. . . . .......XoXo. ",
" ........ .......OoooX. ",
" ... . ...X.X.XXXXoooX  ",
" ......X.X.XXXXXXoooX   ",
" ...X.X.X.XXXXXXXooo    ",
" ..X.X..XXXXXXXXooo     ",
"  X.X.XXXXXXXXXooX      ",
"  .XXXXXXXXXoooX.       ",
"   .XXXXXoooX.          ",
"     .....              ",
"                        ",
"                        "};
/* XPM */
static char *viewshellexpansion_xpm[] = {
"24 24 5 1",
" 	c #ffffff",
".	c #808080",
"X	c #000000",
"o	c #800000",
"O	c #808080",
"    .XXXXXXXXXX..       ",
"  XXXoOOOOoOOOOXXX.     ",
"XXOOOoOOOOoOOOOoO XX    ",
"oOOOOoOOOOoOOOOoOOO X   ",
"oOOOOoOOOOoOOOOoOOOOoX  ",
"oOOOXoXXXXoXXXXoOOOOo X ",
"oXXXOoOOOOoOOOOoXXXXoOX ",
"oOOOOoOOOOoOOOOoOOOOoXO.",
"oOOOOoOOOOoOOOOoOOOOoOXX",
"oOOOOoOOOOoOOOOoOOOOoOOX",
"oOOOOoOOOOoOOOOoOOOOoOOX",
"oXXXXoXXXXoXXXXoXXXXoXXX",
"oOOOOoOOOOoOOOOoOOOOoOOX",
"oOOOOoOOOOoOOOOoOOOOoOOX",
"oOOOOoOOOOoOOOOoOOOOoOXX",
"oOOOOoOOOOoOOOOoOOOOoXO.",
"oXXXOoOOOOoOOOOoXXXXoOX ",
"oOOOXoXXXXoXXXXoOOOOoOX ",
"oOOOOoOOOOoOOOOoOOOOoX. ",
"oOOOOoOOOOoOOOOoOOOOo.  ",
"XXOOOoOOOOoOOOOoOOXX.   ",
"  XXXoOOOOoOOOOXXX..    ",
"    .XXXXXXXXXX..       ",
"                        "};
/* XPM */
static char *viewstarboardpersp_xpm[] = {
"24 24 6 1",
" 	c #ffffff",
".	c #00ffff",
"X	c #008080",
"o	c #0000ff",
"O	c #c0c0c0",
"+	c #ff0000",
"                        ",
"              ..XXoooooo",
"          ..XXoooXXXOOOo",
"        .XoooXXOOOOOOOOo",
"       .ooX+OOOOOOOOOOXo",
"     .ooXOO+OOOOOOOOOOXo",
"    .o+OOOO+OOOOOOOOOOo.",
"   .oX+OOOOO+OOOOOOOOOo.",
"  .oXO+OOOOO+OOOOOOOOOo ",
"  o+OO+OOOOO+OOOOOOOOXo ",
" .o+OO+OOOOOO+OOOOOOOXo ",
" oO+OOO+OOOOO+OOOOOOOo. ",
".oO+OOO+OOOOOO+OOOOOOo. ",
"o+O+OOO+OOOOOO+OOOOOXo  ",
"o+OO+OOO+OOOOOO+OOOOXo  ",
"o+OO+OOO+OOOOOOO+OOOo.  ",
".o+OO+OOO+OOOOOOO++Xo   ",
".o+OO+OOOO+OOOOOOOOo    ",
" o+OOO+OOOO+OOOOOOo     ",
" .o+OOO+OOOO++++oo      ",
"  oX+OOO++++Xooo.       ",
"  .oo+++Xoooo.          ",
"    .oooo..             ",
"                        "};
/* XPM */
static char *viewzoom_xpm[] = {
"24 24 6 1",
" 	c #ff0000",
".	c #c0c0c0",
"X	c #ffffff",
"o	c #000000",
"O	c #800000",
"+	c #808080",
"                  ......",
" XXXXXXXXXXXXXXXX ......",
" oooooooooooooooX  .....",
" XXXXXXXXXXXXXXoX ......",
" XXXXXXXXXXXXXXoX . ....",
" XXXXXXXXXXXXXoXX ......",
" XXXXXXXXXXXXXoXX .. ...",
" XXXXXXXXXXXXoXXX ......",
" XXXXXXXXXXXXoXXX ... ..",
" XXXXXXXXXoooXXXX ......",
" XXXXXXoooXXoXXXX .... .",
" XXXoooXXXXoXXXXX ......",
" oooXXXXXXXoXXXXX ..... ",
" XXXXXXXXXoXXXXXX OOOOOO",
" XXXXXXXXoXXXXXXX XXXXXO",
" XXXXXXooXXXXXXXX +++++O",
" XXXXooXXXXXXXXXX XXXX+O",
"                  XXX+XO",
".. ..........OXXXX XX+XO",
".... ........OXXX++ +XXO",
"...... ......O+++XXX XXO",
"........ ....OXXXXX+X XO",
".......... ..OXXX++XXX O",
"............ OOOOOOOOOOO"};

/* XPM */
static char *zoomin_xpm[] = {
"24 24 4 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"o	c #ffffff",
"               X        ",
"               X        ",
"               X        ",
"       .XXXX.  X        ",
"     .XX.  .XX.X        ",
"    .X.      .X.        ",
"   .X. ooXX   .X.       ",
"   X. o  XX    .XX      ",
"  .X o   XX     XX      ",
"  X. o   XX     .X      ",
"XXX  XXXXXXXXXX  XXXXXXX",
"  X  XXXXXXXXXX  X      ",
"  X.     XX     .X      ",
"  .X     XX     X.      ",
"   X.    XX    .XX      ",
"   .X.   XX   .X.XX     ",
"    .X.      .Xoo.XX    ",
"     .XX.  .XX..oo.XX   ",
"       .XXXX.  ..oo.XX  ",
"               X..oo.XX ",
"               X ..oo.X ",
"               X  ..ooX ",
"               X   ..X  ",
"                        "};

/* XPM */
static char *zoomout_xpm[] = {
"24 24 4 1",
" 	c #c0c0c0",
".	c #808080",
"X	c #000000",
"o	c #ffffff",
"                        ",
"                        ",
"                        ",
"       .XXXX.           ",
"     .XX.  .XX.         ",
"    .X.      .X.        ",
"   .X. oo     .X.       ",
"   X. o        .X       ",
"  .X o          X.      ",
"  X. o          .X      ",
"  X  XXXXXXXXXX  X      ",
"  X  XXXXXXXXXX  X      ",
"  X.            .X      ",
"  .X            X.      ",
"   X.          .XX      ",
"   .X.        .X.XX     ",
"    .X.      .Xoo.XX    ",
"     .XX.  .XX..oo.XX   ",
"       .XXXX.  ..oo.XX  ",
"                ..oo.XX ",
"                 ..oo.X ",
"                  ..ooX ",
"                   ..X  ",
"                        "};

char **pixmap[] = {
iconpilotboat_xpm,
iconworkboat_xpm,
iconyachthull_xpm,
filebuildersoffsets_xpm,
filedynamicwaterline_xpm,
fileexit_xpm,
FileImport_xpm,
filenewhull_xpm,
fileopen_xpm,
fileplot_xpm,
fileprint_xpm,
filesave_xpm,
filewritedxf_xpm,
editcatamaranconvert_xpm,
editcatamaranmovehulls_xpm,
editcopytoclipboard_xpm,
editlineinsert_xpm,
editlineproperties_xpm,
editmultiplyadd_xpm,
editmultiply_xpm,
editorientatelines_xpm,
editsectcentre_xpm,
editsectcontrol_xpm,
editsectdouble_xpm,
editsectedit_xpm,
editsectfollow_xpm,
editsecthalf_xpm,
editsecthelp_xpm,
editsectionadd_xpm,
editsectiondelete_xpm,
editsectionsedit_xpm,
editsectmaster_xpm,
editsectoffset_xpm,
editsectquit_xpm,
editsectredraw_xpm,
editsectshow_xpm,
editsecttextmode_xpm,
editsectundo_xpm,
editsectzoom_xpm,
editstemradius_xpm,
edittransom_xpm,
viewallorthogonal_xpm,
viewbodyplan_xpm,
viewfullpersp_xpm,
viewlinesmooth_xpm,
viewplan_xpm,
viewportpersp_xpm,
viewposition_xpm,
viewprofile_xpm,
viewshaded_xpm,
viewshellexpansion_xpm,
viewstarboardpersp_xpm,
viewzoom_xpm,
staticsbalancehull_xpm,
staticsplotvariables_xpm,
staticssettings_xpm,
staticstabularoutput_xpm,
hullstat_xpm,
draggerritsma_xpm,
dragholtrop_xpm,
dragoortmerrssen_xpm,
dragplot_xpm,
dragsavitskybrown_xpm,
dragsavitsky_xpm,
plateevaluate_xpm,
plateundoruling_xpm,
runcad_xpm,
runcalculator_xpm,
rundos_xpm,
runeditor_xpm,
runfilemanager_xpm,
tankaddtank_xpm,
tankproperties_xpm,
tankstatics_xpm,
confsetcolours_xpm,
confsetfont_xpm,
confsetlinestyles_xpm,
confsetplotter_xpm,
helphull_xpm,
help_xpm,
smalso_xpm,
smcurve_xpm,
smflexibility_xpm,
smignore_xpm,
smmaster_xpm,
smpull_xpm,
smsmooth_xpm,
smvalue_xpm,
zoomin_xpm,
zoomout_xpm,
0
};

#ifndef linux

/*	Convert xpm data to a Windows bitmap	*/

#include "hulldesi.h"

HBITMAP xpmToBitmap(HDC hdc,int ind)
{
	char **pm = pixmap[ind];
	int cols,rows,colours;
	int i,j,k;
	char *p;
	RGBQUAD map[24][24];
	int r,g,b;
	char mapr[128],mapg[128],mapb[128];
	BITMAPINFO bmi;

	memset(mapr,0,128);
	memset(mapg,0,128);
	memset(mapb,0,128);

	sscanf(*pm++,"%d %d %d",&cols,&rows,&colours);
	if(cols != 24 || rows != 24) message("Invalid pixmap size");
	for(i = 0 ; i < colours ; i++) {
		j = **pm;
		p = strchr(*pm,'#') + 1;
		if(p == NULL) {
			message("invalid pixmap colour");
			r = 0;
			g = 0;
			b = 0;
		} else {
			sscanf(p,"%2x%2x%2x",&r,&g,&b);
		}
		mapr[j] = (char) r;
		mapg[j] = (char) g;
		mapb[j] = (char) b;
		pm++;
	}
	for(j = 23 ; j >= 0 ; j--) {
		p = *pm++;
		for(i = 0 ; i < 24 ; i++) {
			k = *p++;
			map[j][i].rgbRed = mapr[k];
			map[j][i].rgbGreen = mapg[k];
			map[j][i].rgbBlue = mapb[k];
		}
	}
	bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
	bmi.bmiHeader.biWidth = 24;
	bmi.bmiHeader.biHeight = 24;
	bmi.bmiHeader.biPlanes = 1;
	bmi.bmiHeader.biBitCount = 32;
	bmi.bmiHeader.biCompression = BI_RGB;
	return CreateDIBitmap(hdc,(BITMAPINFOHEADER *) &bmi,CBM_INIT,map,&bmi,DIB_RGB_COLORS);
}

#endif


